### ISSUE TITLE
Need bitcode enabled static library

### ISSUE THREAD

**Issue by krishnaplivo** [mesibo/mesibowebrtcframework#1]
The current fat static library is not enabled for bitcode. Can u plz share one with bitcode enabled.

**Comment by mesibo** [comment]
We have pulled out bitcode enabled version due to the large size (850+MB) and issues with GitHub/LFS and we are unlikely to release it again. Disable bitcode in your project.

**Comment by krishnaplivo** [comment]
can u plz share the steps so I can compile them on my laptop? I cannot Disable bitcode in my project.

**Comment by mesibo** [comment]
We are unable to help further. Please do not raise this issue again.
