### ISSUE TITLE
Not the architecture being linked

### ISSUE THREAD

**Issue by Hirobreak** [mesibo/mesibowebrtcframework#2]
I'm getting the following error when building my app after installing webRTC using `pod install`:

```
ignoring file /Users/allisson/Documents/Git/febo/febo/Pods/mesibo-webrtc/WebRTC.framework/WebRTC, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/allisson/Documents/Git/febo/febo/Pods/mesibo-webrtc/WebRTC.framework/WebRTC
```

my Xcode version is 10.1

**Comment by mesibo** [comment]
Seems like a broken download. What is the size of WebRTC.framework/WebRTC file? It should be 850+ MB. 

Also, ensure that git LFS (https://git-lfs.github.com/) is installed before downloading.

**Comment by Hirobreak** [comment]
I already installed git LFS but still got the same error. 
I don't have specifically `WebRTC.framework`, inside my pod folder `mesibocall.framework` is downloaded and it is roughly 10MB

**Comment by mesibo** [comment]
If you are using the pod, ensure that you clear the cache after installing the LFS, as describe [here on the CocoaPods GitHub issue tracker](https://github.com/CocoaPods/CocoaPods/issues/4801)

Something like 
       `rm -rf /Users/$USER/Library/Caches/CocoaPods`

Another way is to manually fetch using `git clone` and copy into your project.

**Comment by Hirobreak** [comment]
Thank you! Got it installed with that command!

but i can't seem to import MesiboCall in any swift file, should I use a bridging from objective c?

**Comment by mesibo** [comment]
Awesome! Yes, use the bridging header.

**Comment by Hirobreak** [comment]
Hi, I created the bridging header and added the following line:
`#import <MesiboCall/MesiboCall.h>`
and i'm linking the objective-C bridging header from `Build Settings` but i still can't import MesiboCall, any thoughts on this?

**Comment by Hirobreak** [comment]
Got it working! There is no need to add `import MesiboCall`!
I can make calls successfully, but everytime I answer a call, my app crashes with the following error:
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
```

**Comment by Hirobreak** [comment]
Closing this issue because the build and link of MesiboCall has been resolved
