### ISSUE TITLE
Bitcode enabled

### ISSUE THREAD

**Issue by bolo992** [mesibo/mesibowebrtcframework#4]
Hello, i need framework with bitcode enabled option. Can you provide me somehow, i would really appreciate that :).

**Comment by mesibo** [comment]
Hi, bitcode enabled framework was 850+MB and hence we have discontinued it. Please disable bitcode option in xcode.

**Comment by bolo992** [comment]
I won't disable bitcode because in that case i can't get DSYMS for Firebase Crashlytics.

**Comment by mesibo** [comment]
We only support mesibo here. For any other products, you can ask them.
