### ISSUE TITLE
Linker command failed?

### ISSUE THREAD

**Issue by hansimmmi** [mesibo/mesibowebrtcframework#5]
Hi! Thank you for sharing static library, which we need for our own situation. We've been using WebRTC from cocoa pods(which already deprecated and old) but when we are trying your library as static import, it looks having some issues, which is hard to debug without seeing the source code. Of course these error were not happening for other webRTC library either. Is there something we are missing here?

Again, really appreciate your work and hope to resolve the issue. 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in WebRTC(arm64.o)
  "_VTCompressionSessionCreate", referenced from:
      l6185 in WebRTC(arm64.o)
  "_VTCompressionSessionEncodeFrame", referenced from:
      l6174 in WebRTC(arm64.o)
  "_VTCompressionSessionGetPixelBufferPool", referenced from:
      l6185 in WebRTC(arm64.o)
  "_VTCompressionSessionInvalidate", referenced from:
      l6188 in WebRTC(arm64.o)
  "_VTDecompressionSessionCreate", referenced from:
      l6148 in WebRTC(arm64.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      l6164 in WebRTC(arm64.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      l6151 in WebRTC(arm64.o)
  "_VTDecompressionSessionWaitForAsynchronousFrames", referenced from:
      l6151 in WebRTC(arm64.o)
  "_VTSessionSetProperty", referenced from:
      l6150 in WebRTC(arm64.o)
      l6191 in WebRTC(arm64.o)
      l44640 in WebRTC(arm64.o)
      l44641 in WebRTC(arm64.o)
      l44642 in WebRTC(arm64.o)
      l44643 in WebRTC(arm64.o)
  "_check_session_description_compliance", referenced from:
      l54525 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_AllowFrameReordering", referenced from:
      l6187 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_AverageBitRate", referenced from:
      l6191 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_DataRateLimits", referenced from:
      l6191 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_ExpectedFrameRate", referenced from:
      l6191 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_MaxKeyFrameInterval", referenced from:
      l6187 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_MaxKeyFrameIntervalDuration", referenced from:
      l6187 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      l6187 in WebRTC(arm64.o)
  "_kVTCompressionPropertyKey_RealTime", referenced from:
      l6187 in WebRTC(arm64.o)
  "_kVTDecompressionPropertyKey_RealTime", referenced from:
      l6150 in WebRTC(arm64.o)
  "_kVTEncodeFrameOptionKey_ForceKeyFrame", referenced from:
      l6174 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_3_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_3_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_3_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_4_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_4_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_4_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_5_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_5_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_5_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Baseline_AutoLevel", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_3_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_3_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_3_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_4_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_4_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_4_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_5_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_5_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_5_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_High_AutoLevel", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_3_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_3_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_3_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_4_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_4_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_4_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_5_0", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_5_1", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_5_2", referenced from:
      l6171 in WebRTC(arm64.o)
  "_kVTProfileLevel_H264_Main_AutoLevel", referenced from:
      l6171 in WebRTC(arm64.o)
  "_nw_interface_get_name", referenced from:
      l49232 in WebRTC(arm64.o)
  "_nw_interface_get_type", referenced from:
      l49232 in WebRTC(arm64.o)
  "_nw_path_enumerate_interfaces", referenced from:
      l49231 in WebRTC(arm64.o)
  "_nw_path_get_status", referenced from:
      l49231 in WebRTC(arm64.o)
  "_nw_path_monitor_cancel", referenced from:
      l49235 in WebRTC(arm64.o)
  "_nw_path_monitor_create", referenced from:
      l49230 in WebRTC(arm64.o)
  "_nw_path_monitor_set_queue", referenced from:
      l49230 in WebRTC(arm64.o)
  "_nw_path_monitor_set_update_handler", referenced from:
      l49230 in WebRTC(arm64.o)
  "_nw_path_monitor_start", referenced from:
      l49230 in WebRTC(arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hansimmmi** [comment]
Further investigation, it turns out the app should import videoToolbox and GLKKit. Most of the liker issues are gone with those changes, but _check_session_description_compliance is still being used. On further research, your own framework has the reference.. in this case this library can't be used independently?

**Comment by mesibo** [comment]
Hi, `_check_session_description_compliance` is part of the mesibo framework so currently you can use this WebRTC library only with mesibo.

**Comment by hansimmmi** [comment]
Thank for confirming!
